package xyz

import (
	"bytes"
	"fmt"

	"smiles3d/mol"
)

// WriteXYZ generates an XYZ format string for a molecule.
func WriteXYZ(m *mol.Mol) string {
	var buf bytes.Buffer

	// First line: number of atoms
	buf.WriteString(fmt.Sprintf("%d\n", m.NumAtoms()))

	// Second line: comment
	buf.WriteString("Generated by custom Go SMILES->XYZ pipeline\n")

	// Atom lines: Symbol X Y Z
	for i := 1; i <= m.NumAtoms(); i++ {
		a := m.GetAtom(i)
		sym := a.Symbol()
		buf.WriteString(fmt.Sprintf("%-2s %10.5f %10.5f %10.5f\n", sym, a.X, a.Y, a.Z))
	}

	return buf.String()
}
